#!/usr/bin/env bash

#check for bucket name.
if [ -z "$1" ]; then
    echo "there needs to be a bucket name e.g. ./bucket my-bucet-name."
    exit 1
fi


aws s3api create-bucket --bucket $1 \
--region ap-south-1 \
--create-bucket-configuration LocationConstraint=ap-south-1