#!/usr/bin/env bash

echo "delete bucket"

#check for bucket name.
if [ -z "$1" ]; then
    echo "there needs to be a bucket name e.g. ./bucket my-bucet-name."
    exit 1
fi


aws s3api delete-bucket --bucket $1 
